# Site settings
title: MelBlog
header-img: img/home-bg.jpg
email: melanie.bats@obeo.fr
copyright_name: MÃ©lanie Bats
description: "Eclipse, modeling and other things"
baseurl: ""
url: "http://mbats.github.io"
twitter_username: melaniebats
github_username:  mbats
facebook_username:  
email_username:  melanie.bats@obeo.fr

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
